package BatchProcessing.springbatchpurge.model;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum SpringDataPurgeEntity {

    BATCH_STEP_EXECUTION_CONTEXT("DELETE FROM BATCH_STEP_EXECUTION_CONTEXT WHERE STEP_EXECUTION_ID IN (SELECT STEP_EXECUTION_ID FROM BATCH_STEP_EXECUTION WHERE JOB_EXECUTION_ID IN ( SELECT JOB_EXECUTION_ID FROM BATCH_JOB_EXECUTION WHERE JOB_INSTANCE_ID = ?))"),
    BATCH_STEP_EXECUTION("DELETE FROM BATCH_STEP_EXECUTION WHERE JOB_EXECUTION_ID IN ( SELECT JOB_EXECUTION_ID FROM BATCH_JOB_EXECUTION WHERE JOB_INSTANCE_ID = ?)"),
    BATCH_JOB_EXECUTION_CONTEXT("DELETE FROM BATCH_JOB_EXECUTION_CONTEXT WHERE JOB_EXECUTION_ID IN ( SELECT JOB_EXECUTION_ID FROM BATCH_JOB_EXECUTION WHERE  JOB_INSTANCE_ID = ?)"),
    BATCH_JOB_EXECUTION_PARAMS("DELETE FROM BATCH_JOB_EXECUTION_PARAMS WHERE JOB_EXECUTION_ID IN ( SELECT JOB_EXECUTION_ID FROM BATCH_JOB_EXECUTION WHERE JOB_INSTANCE_ID = ?)"),
    BATCH_JOB_EXECUTION("DELETE FROM BATCH_JOB_EXECUTION WHERE JOB_EXECUTION_ID = ?"),
    BATCH_JOB_INSTANCE("DELETE FROM BATCH_JOB_INSTANCE WHERE JOB_INSTANCE_ID NOT IN (SELECT JOB_INSTANCE_ID FROM BATCH_JOB_EXECUTION)");

    private String purgeQuery;

}
